# Generated by Django 4.1.2 on 2022-10-12 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 7, 4, 42, 307328)),
        ),
    ]
