# Generated by Django 4.1.2 on 2022-10-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0004_alter_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
