# Generated by Django 4.1.2 on 2022-10-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0005_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
